### ISSUE TITLE
Installing Phoebe 1 on Ubuntu 

### ISSUE THREAD

**Issue by horvatm** [phoebe-project/phoebe1#1]
# Installation tutorial for Phoebe1 on Ubuntu
## Requirements

Using ubuntu 16.04.

installing essentials build tools
`sudo apt-get install build-essential gfortran`

installing lexical analyser, yacc grammar parser
`sudo apt-get install flex bison`

installing gnu-scientific library
`sudo apt-get install libgsl-dev`

installing gtk-doc
`sudo apt-get install gtk-doc-tools`

installing libglade
`sudo apt-get install libglade2-dev`

installing gnuplot
`sudo apt-get install gnuplot`

installing gnu-readline
`sudo apt-get install libreadline-dev`
## Installation

The results of compilation will be installed in /usr/local/lib/ and  /usr/local/lib/phoebe-plugins

installing phoebe-lib

```
cd phoebe-lib
./configure
make
sudo make install
```

installing phoebe-gui

```
cd phoebe-gui
./configure
make
sudo make install
```

installing phoebe-scripter

```
cd phoebe-scripter
./configure
make
sudo make install
```

installing phoebe-plugins

```
cd phoebe-plugins
./configure
make
sudo make install
```

installing phoebe-py

```
python setup.py build
python setup.py install --user
```

re-reading linux libraries

> sudo ldconfig
## Running

```
cd phoebe-py 

python phoebe.py 
PHOEBE-lib warning: configuration file not found, reverting to defaults.
PHOEBE configuration file not found.
Traceback (most recent call last):
  File "phoebe.py", line 63, in <module>
    backend.configure()
SystemError: error return without exception set
```

Is this normal?  Is there any tutorial? @kecnry @aprsa 

Additionally files with name "-" are appearing in directories, which are quite annoying.  

I've checked that all compilations can be done also with clang compiler 
CC=clang ./configure
so it should work also on OS X

**Comment by aprsa** [comment]
You have to run any of the phoebe frontends first (phoebe-gui, phoebe-scripter) so that they create a configuration file. Alternatively, you can create a configuration file manually. Long story short, phoebe-py is just a simple wrapper, it needs a genuine front-end to be run first.
