### ISSUE TITLE
Limb-Darkening error phoebeBackend

### ISSUE THREAD

**Issue by colej** [phoebe-project/phoebe1#11]
Hi, 

When using phoebeBackend, I have the issue that using phoebe.updateLD() successfully updates the coefficients of the primary (for both the bolometric and LC dependent terms) but sets the coefficients of the secondary to 0. This occurs for all limb-darkening laws and for at least the Kepler, TESS, and Cousins-I passbands.

Interestingly, when I do this with phoebe GUI, it updates all coefficients without any issue. 

Some example output (taken from test.py in the phoebe-py/ directory):

```
Original bolometric LD coefficients: 0.5 0.5 0.5 0.5
LCs: 1; RVs: 2; LD model: Logarithmic law
T1=6000, T2=5200; logg1=4.007, logg2=5.010; met1=0.000, met2=0.000
 Updated bolometric LD coefficients: 0.689 0.16015845658 0.0 0.0
```
I've noticed that the values for logg1 and logg2 output by the function updateLD() are discrepant to those reported when I call phoebe.getpar('phoebe_logg1') (or 2). Could it be that the routine thinks that it is outside of the interpolation range in the tables?

cheers,
cole

**Comment by aprsa** [comment]
Hi Cole, thanks for reporting this -- and sorry it took me this long to take a closer look. The updateLD() function indeed calculates logg values from potentials, sma, period, mass ratio, eccentricity and synchronicity parameters rather than taking the passed logg parameters. Could you possibly send me the script to reproduce so that I can investigate further?

**Comment by colej** [comment]
Hi Andrej, 

This was made with the test.py script that comes with the phoebe1 stable release in the phoebe-py directory.

**Comment by aprsa** [comment]
Turns out it really was just a parameter out-of-bounds situation. I significantly improved error handling of LDs in the wrapper.
