### ISSUE TITLE
Unable to plot any graph on Phoebe legacy v0.31 on Windows.

### ISSUE THREAD

**Issue by AdarshKrishna99** [phoebe-project/phoebe1#22]
Hello,
I am trying to plot an LC on Phoebe legacy versions 0.31 and 0.31a. I am unable to plot the LC on either versions even for the built-in UVLeo binary system. The software was downloaded (as a .exe file) from the website for Windows environment. Please help me through this using the attached image. 
-Adarsh.
![Screenshot 2023-04-29 224416](https://user-images.githubusercontent.com/131899802/235315277-ee0d8705-06cd-4b73-ba6c-ea5dc3595d11.png)

**Comment by aprsa** [comment]
Hi Adarsh, unfortunately we no longer maintain the legacy GUI (beyond science bug fixes), especially for the windows port that was never really supported. I pinged Patrick, the person who did the port, and he suggested that you might not be using the latest version; [this is the latest version](http://aprsa.villanova.edu/files/phoebe0.32-setup.exe) that he ported to windows. If that doesn't work, then perhaps it's time to upgrade to phoebe 2.4.
