### ISSUE TITLE
PhoebeBackend not found

### ISSUE THREAD

**Issue by nagarajvernekar30** [phoebe-project/phoebe1#23]
Hello, 

While I was trying to use the python code that runs MCMC estimator for PHOEBE 1, I got an error stating 'PhoebeBackend mofule not found'. But I already have a running version of PHOEBE 1 downloaded from Github and installed as mentioned. I ran ./compile, make and make install for lib, scripter and gui. Do i need to run some other once also? to get PhoebeBackend.

**Comment by nagarajvernekar30** [comment]
I just ran python setup.py build inside the python-py folder. It ran succesfully but still I get the error of phoebeBackend not found.

**Comment by kecnry** [comment]
Did you also run `python setup.py install` (you'll probably need `--user` or admin rights) as well?  Can you import `phoebeBackend` directly in python?

**Comment by nagarajvernekar30** [comment]
Yes, I just created a new environment with python 2.7 and did the whole new install of phoebe (lib, scripter, gui and plugin). I also ran python setup.py install  but still get the same module not found in direct python. 

I have not used the --user.

**Comment by kecnry** [comment]
Can you attach the logs from calling build and install?  It might also be worth trying in python 3 instead (python 2.7 is quite outdated and not supported by most packages).

**Comment by nagarajvernekar30** [comment]
When I try to run setup.py using python 3, I get the following error: 

`running build
running build
running build_ext
building 'phoebeBackend' extension
.
.
.
.
/home/adorea/miniconda3/compiler_compat/ld: cannot find -lphoebe
collect2: error: ld returned 1 exit status
error: command '/home/adorea/mesasdk/bin/gcc' failed with exit code 1`


But when I use python2.7, I get the output as : 
 `running build
running build
running build_ext
`

**Comment by nagarajvernekar30** [comment]
Hello, 

I am really sorry for this, but I realized my mistake. I only built the setup.py but did not install it. 

Thank you for addressing my issue so quickly.
