### ISSUE TITLE
gui plotting does not respond correctly when attributes are changed

### ISSUE THREAD

**Issue by bpablo** [phoebe-project/phoebe1#5]
When trying to change the "color" attribute for a light curve a new lc dataset is added, and the error message:

"Observations for curve 2 failed to open and cannot be plotted. Please review the information given in the Data tab."

Even after deleting the added curve phoebe will not respond properly until the gui is restarted.

**Comment by aprsa** [comment]
Hi @bpablo, I can't reproduce this; could you please provide me with step-by-step list of what you do to have this happen?

**Comment by bpablo** [comment]
1. Open up a file with 2 lightcurves attached.
2. Change the synthetic color on one and then on the other. 
3.) You end up with an extra dataset.
![Screen Shot 2020-08-12 at 3 53 53 PM](https://user-images.githubusercontent.com/7862910/90061647-6aaa6f80-dcb4-11ea-9108-e2baf97fcecf.png)
![Screen Shot 2020-08-12 at 3 54 01 PM](https://user-images.githubusercontent.com/7862910/90061673-7433d780-dcb4-11ea-89a4-5019410cf545.png)

**Comment by aprsa** [comment]
hmmm, I still can't reproduce. This is on a mac, right? Are you using the latest version from git master?

**Comment by aprsa** [comment]
@kecnry, @gecheline, can you guys please try to reproduce on a linux and mac, respectively?

**Comment by kecnry** [comment]
I cannot produce with the version I have installed with LC synthetics only.  Maybe sharing the phoebe file would help?  It also looks from the screenshot like obs color was changed instead of syn color, does it happen for both?

**Comment by aprsa** [comment]
@bpablo, can you please edit phoebe-gui/glade/phoebe_cairo.glade:11174 and change reorderable property on phoebe_lc_plot_treeview to False? Then reinstall and try again. Does that change anything?

**Comment by bpablo** [comment]
@aprsa  changing the reorderable property appears to have fixed the issue. I updated to the latest version first, so I can confirm that it was that specific fix that helped.
